plugins { id 'com.android.application' }

android {
    namespace 'com.musyfit.watch'
    compileSdk 35
    defaultConfig {
        applicationId 'com.musyfit.watch'
        minSdk 23
        targetSdk 35
        versionCode 30
        versionName '3.0'
    }
}

dependencies {
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
}
